feat: check mime type of urls before adding to request queue
GovTechSG/purple-a11y pull request #377
Opened 2024-06-30 02:14 UTC by shioju

This PR adds a check for the mime type of each URL before they are added to the request queue (for HTML and PDF) or cancelled (to avoid the crawler downloading content e.g. .zip files) which cannot be processed.

This is done in the `transformRequestFunction`, which unfortunately must be synchronous, based on [how crawlee is using it](https://github.com/apify/crawlee/blob/d81d4813c33b4a405daa1a151bd507ef23cd9409/packages/core/src/enqueue_links/enqueue_links.ts#L365-L369). Therefore, we're using a synchronous HEAD request for this, which is usually avoided in production environments, but this is the last resort.

- [ ] I've kept this PR as small as possible (~500 lines) by splitting it into PRs with manageable chunks of code
- [ ] I've requested reviews from 1 reviewer
- [ ] I've tested existing features (website scan, sitemap, custom flow) in both node index and cli
- [ ] I've synced this fork with GovTechSG repo
- [ ] I've added/updated unit tests
- [ ] I've added/updated any necessary dependencies in `package[-lock].json` `npm audit`, portable installation on GitHub Actions

2024-07-08 01:02 UTC, shioju commented
> https://masnet.mas.gov.sg/portal/masnet/vmedia/get/?path=1002/application-starter-guide.zip

In this case, if you do a HEAD request to the above, the `content-type` header says it's `text/html`, probably due to a misconfiguration on their server.

If we cannot trust the `content-type`, another way is to download the first 4 bytes and check the magic number. Unfortunately, I couldn't find another library that does synchronous downloads that also supports range downloads. So the other way around this is to fork `crawler` and create a version that supports asynchronous `transformRequestFunction`.

2024-07-08 05:32 UTC, younglim commented
@shioju agreed I can't find any in-built easy way to get magic number without downloading the entire file. Let me mule over it for a while this week for potential solution or accept the limitation of what we have

2024-07-11 02:18 UTC, younglim commented
Will accept the limitations of content-type checking for now - specifically when a web server returns `text/html` when it should not for other file types.

2024-07-11 02:21 UTC, younglim approved these changes

2024-07-13 04:13 UTC, younglim requested changes
When checking magic number, you need to check if axios can actually reach the page.  Cuz on enterprise or proxied environment, you need to fallback axios to web browser.  The other case is when there is basic-auth protected site, you need to send the encoded URL.  

The easiest, least tedious handling of the above edge cases is to check for the appropriate error axios response - i.e. if axios fails to get the download stream going, not automatically assume it is not a zip file. I.e. fallback to checking content-type.

2024-07-15 02:50 UTC, younglim requested changes
Needs type fixes:

```
src/combine.ts:176:9 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'EnqueueStrategy'.

176         strategy,
            ~~~~~~~~

src/crawlers/crawlDomain.ts:28:21 - error TS2307: Cannot find module 'sync-request-curl' or its corresponding type declarations.

28 import request from 'sync-request-curl';
                       ~~~~~~~~~~~~~~~~~~~

src/crawlers/crawlDomain.ts:163:9 - error TS2322: Type '(req: RequestOptions) => Promise<RequestOptions | null>' is not assignable to type 'RequestTransform'.
  Type 'Promise<RequestOptions<Dictionary>>' is not assignable to type 'false | RequestOptions<Dictionary>'.

163         transformRequestFunction: async (req: RequestOptions): Promise<RequestOptions | null> => {
            ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@crawlee/core/enqueue_links/enqueue_links.d.ts:107:5
    107     transformRequestFunction?: RequestTransform;
            ~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from property 'transformRequestFunction' which is declared here on type 'EnqueueLinksOptions'

src/crawlers/crawlDomain.ts:173:57 - error TS2339: Property 'href' does not exist on type 'string'.

173           if (urlsCrawled.scanned.some(item => item.url.href === req.url)) {
                                                            ~~~~

src/crawlers/crawlDomain.ts:208:83 - error TS2339: Property 'href' does not exist on type 'string'.

208       const isAlreadyScanned: boolean = urlsCrawled.scanned.some(item => item.url.href === newPageUrl);
                                                                                      ~~~~

src/crawlers/crawlDomain.ts:448:55 - error TS2339: Property 'href' does not exist on type 'string'.

448         if (urlsCrawled.scanned.some(item => item.url.href === request.url)) {
                                                          ~~~~

src/crawlers/crawlDomain.ts:548:51 - error TS2339: Property 'href' does not exist on type 'string'.

548               item => (item.actualUrl || item.url.href) === request.loadedUrl,
                                                      ~~~~

src/npmIndex.ts:139:30 - error TS2345: Argument of type '{ url: string; pageTitle: string; }' is not assignable to parameter of type '{ url: string; actualUrl: string; pageTitle: string; }'.
  Property 'actualUrl' is missing in type '{ url: string; pageTitle: string; }' but required in type '{ url: string; actualUrl: string; pageTitle: string; }'.

139     urlsCrawled.scanned.push({
                                 ~
140       url: urlWithoutAuth(res.pageUrl).toString(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
141       pageTitle: `${pageIndex}: ${res.pageTitle}`,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
142     });
    ~~~~~

  src/constants/constants.ts:187:27
    187   scanned: { url: string; actualUrl: string; pageTitle: string }[] = [];
                                  ~~~~~~~~~
    'actualUrl' is declared here.


Found 8 errors in 3 files.

Errors  Files
     1  src/combine.ts:176
     6  src/crawlers/crawlDomain.ts:28
     1  src/npmIndex.ts:139
```

2024-08-01 08:35 UTC, younglim commented
@shioju can you work on this?

2024-08-04 10:29 UTC, shioju commented
> @shioju can you work on this?

@younglim I rebased with master and fixed type errors.

2024-08-05 03:50 UTC, younglim commented
@shioju remaining types:

```
src/crawlers/pdfScanFunc.ts:274:36 - error TS2345: Argument of type '{ url: string; pageTitle: string; }' is not assignable to parameter of type '{ url: string; actualUrl: string; pageTitle: string; }'.
  Property 'actualUrl' is missing in type '{ url: string; pageTitle: string; }' but required in type '{ url: string; actualUrl: string; pageTitle: string; }'.

274           urlsCrawled.scanned.push({ url: url, pageTitle });
                                       ~~~~~~~~~~~~~~~~~~~~~~~

  src/constants/constants.ts:187:27
    187   scanned: { url: string; actualUrl: string; pageTitle: string }[] = [];
                                  ~~~~~~~~~
    'actualUrl' is declared here.
    ```

2024-08-05 04:02 UTC, younglim commented
I fixed remaining types https://github.com/GovTechSG/purple-a11y/pull/377/commits/c6f3f6f1b29fbcf251933d65b641a4526495547e

```
src/crawlers/pdfScanFunc.ts:274:36 - error TS2345: Argument of type '{ url: string; pageTitle: string; }' is not assignable to parameter of type '{ url: string; actualUrl: string; pageTitle: string; }'.
  Property 'actualUrl' is missing in type '{ url: string; pageTitle: string; }' but required in type '{ url: string; actualUrl: string; pageTitle: string; }'.

274           urlsCrawled.scanned.push({ url: url, pageTitle });
                                       ~~~~~~~~~~~~~~~~~~~~~~~

  src/constants/constants.ts:187:27
    187   scanned: { url: string; actualUrl: string; pageTitle: string }[] = [];
                                  ~~~~~~~~~
    'actualUrl' is declared here.
    ```

2024-08-05 04:04 UTC, younglim approved these changes

2024-08-05 04:04 UTC, merged